// The single source of truth for which of the base game's ~124
// `game/in_game/common/` category folders (plus `game_concepts` under
// `main_menu/common/`) are included in the Encyclopedia, which domain
// group each included category belongs to, and why an excluded one is
// excluded. Every category is accounted for here — none silently
// dropped (spec FR-007) — per research.md §3: a committed, reviewable
// table, not a runtime heuristic.
//
// Where a category matches one of the game's own official Europedia
// pages (`main_menu/localization/english/encyclopedia_l_english.yml`'s
// `ENCYCLOPEDIA_PAGE_*` keys — research.md §8), its `label` uses the
// game's own wording rather than one invented here.
import type { CategoryAssignment } from "./types";

export const GAME_CONCEPTS_CATEGORY_ID = "game_concepts";

export const CATEGORY_ASSIGNMENTS: CategoryAssignment[] = [
  { id: "advances", excluded: false, domainGroup: "government-society", label: "Advances" },
  { id: "age", excluded: false, domainGroup: "world-events", label: "Ages" },
  { id: "ai_diplochance", excluded: true, reason: "AI-internal diplomacy scoring, not player-facing" },
  { id: "ai_personalities", excluded: true, reason: "AI-internal behavior tuning, not player-facing" },
  { id: "ai_scripted_expansion_score", excluded: true, reason: "AI-internal scoring table" },
  { id: "ai_scripted_expansion_target", excluded: true, reason: "AI-internal scoring table" },
  { id: "alert_descriptions", excluded: true, reason: "Internal UI alert text definitions, not a reference concept" },
  { id: "area_preferences", excluded: true, reason: "AI-internal targeting weights" },
  { id: "artist_types", excluded: false, domainGroup: "culture-religion-characters", label: "Artists" },
  { id: "artist_work", excluded: false, domainGroup: "culture-religion-characters", label: "Artist Work" },
  { id: "attribute_columns", excluded: true, reason: "Internal UI table layout configuration" },
  { id: "auto_modifiers", excluded: true, reason: "Internal scripted-modifier plumbing, not a player concept" },
  { id: "avatars", excluded: false, domainGroup: "culture-religion-characters", label: "Avatars" },
  { id: "biases", excluded: true, reason: "Internal AI/character bias scoring" },
  { id: "building_categories", excluded: false, domainGroup: "economy-production", label: "Building Categories" },
  { id: "building_types", excluded: false, domainGroup: "economy-production", label: "Buildings" },
  { id: "bureaucracies", excluded: false, domainGroup: "government-society", label: "Bureaucracies" },
  { id: "cabinet_actions", excluded: false, domainGroup: "government-society", label: "Cabinet Actions" },
  { id: "casus_belli", excluded: false, domainGroup: "military-diplomacy", label: "Casus Belli" },
  { id: "character_interactions", excluded: false, domainGroup: "culture-religion-characters", label: "Character Interactions" },
  { id: "child_educations", excluded: false, domainGroup: "culture-religion-characters", label: "Child Educations" },
  { id: "chivalric_orders", excluded: false, domainGroup: "military-diplomacy", label: "Chivalric Orders" },
  { id: "climates", excluded: false, domainGroup: "world-events", label: "Climates" },
  { id: "country_description_categories", excluded: true, reason: "Internal UI text categorization" },
  { id: "country_interactions", excluded: false, domainGroup: "military-diplomacy", label: "Country Interactions" },
  { id: "country_ranks", excluded: false, domainGroup: "government-society", label: "Country Ranks" },
  { id: "culture_groups", excluded: false, domainGroup: "culture-religion-characters", label: "Culture Groups" },
  { id: "cultures", excluded: false, domainGroup: "culture-religion-characters", label: "Cultures" },
  { id: "customizable_localization", excluded: true, reason: "Internal templated-text plumbing" },
  { id: "death_reason", excluded: false, domainGroup: "culture-religion-characters", label: "Death Reasons" },
  { id: "designated_heir_reason", excluded: false, domainGroup: "government-society", label: "Designated Heir Reasons" },
  { id: "diplomatic_costs", excluded: false, domainGroup: "military-diplomacy", label: "Diplomatic Costs" },
  { id: "disasters", excluded: false, domainGroup: "world-events", label: "Disasters" },
  { id: "diseases", excluded: false, domainGroup: "world-events", label: "Diseases" },
  { id: "effect_localization", excluded: true, reason: "Internal script-effect text templates" },
  { id: "employment_systems", excluded: false, domainGroup: "economy-production", label: "Employment Systems" },
  { id: "estate_privileges", excluded: false, domainGroup: "government-society", label: "Estate Privileges" },
  { id: "estates", excluded: false, domainGroup: "government-society", label: "Estate Types" },
  { id: "ethnicities", excluded: false, domainGroup: "culture-religion-characters", label: "Ethnicities" },
  { id: "formable_countries", excluded: false, domainGroup: "government-society", label: "Formable Countries" },
  { id: "generic_action_ai_lists", excluded: true, reason: "AI-internal action-list plumbing" },
  { id: "generic_actions", excluded: true, reason: "Internal action-definition plumbing, low standalone reference value" },
  { id: "genes", excluded: false, domainGroup: "culture-religion-characters", label: "Genes" },
  { id: "gods", excluded: false, domainGroup: "culture-religion-characters", label: "Gods" },
  { id: "goods", excluded: false, domainGroup: "economy-production", label: "Goods" },
  { id: "goods_demand", excluded: false, domainGroup: "economy-production", label: "Goods Demand" },
  { id: "goods_demand_category", excluded: false, domainGroup: "economy-production", label: "Goods Demand Categories" },
  { id: "government_reforms", excluded: false, domainGroup: "government-society", label: "Government Reforms" },
  { id: "government_types", excluded: false, domainGroup: "government-society", label: "Government Types" },
  { id: "hegemons", excluded: false, domainGroup: "military-diplomacy", label: "Hegemons" },
  { id: "heir_selections", excluded: false, domainGroup: "government-society", label: "Heir Selections" },
  { id: "historical_scores", excluded: true, reason: "Internal scoring/leaderboard weighting, not a browsable concept" },
  { id: "holy_site_types", excluded: false, domainGroup: "culture-religion-characters", label: "Holy Site Types" },
  { id: "holy_sites", excluded: false, domainGroup: "culture-religion-characters", label: "Holy Sites" },
  { id: "institution", excluded: false, domainGroup: "government-society", label: "Institutions" },
  { id: "insults", excluded: true, reason: "Flavor-text string list, not a mechanic" },
  { id: "international_organization_land_ownership_rules", excluded: true, reason: "Internal rules plumbing, covered conceptually by international_organizations" },
  { id: "international_organization_payments", excluded: false, domainGroup: "military-diplomacy", label: "International Organization Payments" },
  { id: "international_organization_special_statuses", excluded: false, domainGroup: "military-diplomacy", label: "International Organization Special Statuses" },
  { id: "international_organizations", excluded: false, domainGroup: "military-diplomacy", label: "International Organization Types" },
  { id: "join_war_rules", excluded: true, reason: "Internal rules plumbing" },
  { id: "language_families", excluded: false, domainGroup: "culture-religion-characters", label: "Language Families" },
  { id: "languages", excluded: false, domainGroup: "culture-religion-characters", label: "Languages" },
  { id: "laws", excluded: false, domainGroup: "government-society", label: "Laws" },
  { id: "levies", excluded: false, domainGroup: "military-diplomacy", label: "Levies" },
  { id: "location_ranks", excluded: false, domainGroup: "government-society", label: "Location Ranks" },
  { id: "mission_task_defs", excluded: true, reason: "Internal mission-scripting plumbing" },
  { id: "missions", excluded: false, domainGroup: "world-events", label: "Missions" },
  { id: "movements", excluded: false, domainGroup: "world-events", label: "Movements" },
  { id: "music_player_tracks", excluded: true, reason: "Audio asset listing, not gameplay reference" },
  { id: "on_action", excluded: true, reason: "Internal scripted event-hook plumbing" },
  { id: "parliament_agendas", excluded: false, domainGroup: "government-society", label: "Parliament Agendas" },
  { id: "parliament_issues", excluded: false, domainGroup: "government-society", label: "Parliament Issues" },
  { id: "parliament_types", excluded: false, domainGroup: "government-society", label: "Parliament Types" },
  { id: "peace_treaties", excluded: false, domainGroup: "military-diplomacy", label: "Peace Treaties" },
  { id: "persistent_dna", excluded: true, reason: "Internal character-generation data" },
  { id: "policies", excluded: false, domainGroup: "government-society", label: "Policies" },
  { id: "pop_types", excluded: false, domainGroup: "economy-production", label: "Social Classes" },
  { id: "prices", excluded: false, domainGroup: "economy-production", label: "Prices" },
  { id: "production_methods", excluded: false, domainGroup: "economy-production", label: "Production Methods" },
  { id: "rebel_demands", excluded: false, domainGroup: "world-events", label: "Rebel Demands" },
  { id: "recruitment_method", excluded: false, domainGroup: "military-diplomacy", label: "Recruitment Methods" },
  { id: "regencies", excluded: false, domainGroup: "government-society", label: "Regency Types" },
  { id: "religion_groups", excluded: false, domainGroup: "culture-religion-characters", label: "Religion Groups" },
  { id: "religions", excluded: false, domainGroup: "culture-religion-characters", label: "Religions" },
  { id: "religious_aspects", excluded: false, domainGroup: "culture-religion-characters", label: "Religious Aspects" },
  { id: "religious_factions", excluded: false, domainGroup: "culture-religion-characters", label: "Religious Factions" },
  { id: "religious_figures", excluded: false, domainGroup: "culture-religion-characters", label: "Religious Figures" },
  { id: "religious_focuses", excluded: false, domainGroup: "culture-religion-characters", label: "Religious Focuses" },
  { id: "religious_schools", excluded: false, domainGroup: "culture-religion-characters", label: "Religious Schools" },
  { id: "resolutions", excluded: false, domainGroup: "military-diplomacy", label: "Resolutions" },
  { id: "rival_criteria", excluded: true, reason: "Internal AI rivalry-scoring plumbing" },
  { id: "road_types", excluded: false, domainGroup: "economy-production", label: "Road Types" },
  { id: "script_values", excluded: true, reason: "Internal scripting constants" },
  { id: "scriptable_hints", excluded: true, reason: "Internal UI tooltip-hint plumbing" },
  { id: "scripted_country_names", excluded: true, reason: "Internal name-generation lists" },
  { id: "scripted_diplomatic_objectives", excluded: true, reason: "Internal AI objective scripting" },
  { id: "scripted_effects", excluded: true, reason: "Internal scripting library" },
  { id: "scripted_geography", excluded: true, reason: "Internal scripting helper definitions" },
  { id: "scripted_guis", excluded: true, reason: "Internal UI scripting" },
  { id: "scripted_lists", excluded: true, reason: "Internal scripting library" },
  { id: "scripted_modifiers", excluded: true, reason: "Internal scripting library" },
  { id: "scripted_relations", excluded: true, reason: "Internal scripting library" },
  { id: "scripted_rules", excluded: true, reason: "Internal scripting library" },
  { id: "scripted_triggers", excluded: true, reason: "Internal scripting library" },
  { id: "situations", excluded: false, domainGroup: "world-events", label: "Situations" },
  { id: "societal_values", excluded: false, domainGroup: "government-society", label: "Societal Values" },
  { id: "subject_military_stances", excluded: false, domainGroup: "military-diplomacy", label: "Subject Military Stances" },
  { id: "subject_types", excluded: false, domainGroup: "military-diplomacy", label: "Subject Types" },
  { id: "tests", excluded: true, reason: "Developer test data, not game content" },
  { id: "topography", excluded: false, domainGroup: "world-events", label: "Topographies" },
  { id: "town_rights", excluded: false, domainGroup: "government-society", label: "Urban Rights" },
  { id: "town_setups", excluded: true, reason: "Internal city-generation setup data, low standalone reference value" },
  { id: "trait_flavor", excluded: true, reason: "Internal flavor-text variants for traits, covered by the traits category itself" },
  { id: "traits", excluded: false, domainGroup: "culture-religion-characters", label: "Traits" },
  { id: "trigger_localization", excluded: true, reason: "Internal scripting-trigger text templates" },
  { id: "tutorial_lesson_chains", excluded: true, reason: "Internal tutorial sequencing, not reference content" },
  { id: "tutorial_lessons", excluded: true, reason: "Tutorial UI flow content, not an encyclopedia concept" },
  { id: "unit_abilities", excluded: false, domainGroup: "military-diplomacy", label: "Unit Abilities" },
  { id: "unit_categories", excluded: false, domainGroup: "military-diplomacy", label: "Unit Categories" },
  { id: "unit_formation_preference", excluded: true, reason: "AI-internal formation-preference scoring" },
  { id: "unit_types", excluded: false, domainGroup: "military-diplomacy", label: "Unit Types" },
  { id: "vegetation", excluded: false, domainGroup: "world-events", label: "Vegetation" },
  { id: "wargoals", excluded: false, domainGroup: "military-diplomacy", label: "War Goals" },

  // Lives under `main_menu/common/`, not `in_game/common/` — the game's
  // own hand-written mechanics glossary (research.md §8).
  { id: GAME_CONCEPTS_CATEGORY_ID, excluded: false, domainGroup: "government-society", label: "Game Concepts" },
];

export const DOMAIN_GROUP_LABELS: Record<string, string> = {
  "economy-production": "Economy & Production",
  "government-society": "Government & Society",
  "culture-religion-characters": "Culture, Religion & Characters",
  "military-diplomacy": "Military & Diplomacy",
  "world-events": "World & Events",
};
