// Readable names for the raw keys the save stores on a country: laws,
// policies, privileges, estates, pop types, subject types, and the label
// of a government type's "government power" (specs/018-country-factbook-
// tabs research.md R1/R8). `countryNames.json` is generated by
// tools/country-names/generate.ts from the encyclopedia data and the
// game's own localization. A key it doesn't know is humanized, never
// shown raw.
import names from "./countryNames.json";

const GENERIC_GOVERNMENT_POWER = "Government Power";

export function humanizeKey(key: string): string {
  return key
    .split("_")
    .filter(Boolean)
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join(" ");
}

function lookup(table: Record<string, string>, key: string): string {
  return table[key] ?? humanizeKey(key);
}

/** "Legitimacy" for a monarchy, "Devotion" for a theocracy, etc. */
export function governmentPowerLabel(governmentType: string | null): string {
  if (!governmentType) return GENERIC_GOVERNMENT_POWER;
  return (names.governmentPowers as Record<string, string>)[governmentType] ?? GENERIC_GOVERNMENT_POWER;
}

export function lawName(lawKey: string): string {
  return lookup(names.laws, lawKey);
}

export function policyName(policyKey: string): string {
  return lookup(names.policies, policyKey);
}

export function privilegeName(privilegeKey: string): string {
  const entry = (names.privileges as Record<string, { name: string }>)[privilegeKey];
  return entry?.name ?? humanizeKey(privilegeKey);
}

/** The estate key (e.g. `burghers_estate`) a privilege belongs to. */
export function privilegeEstate(privilegeKey: string): string | null {
  const entry = (names.privileges as Record<string, { estate: string | null }>)[privilegeKey];
  return entry?.estate ?? null;
}

export function estateName(estateKey: string): string {
  return lookup(names.estates, estateKey);
}

export function popTypeName(popTypeKey: string): string {
  return lookup(names.popTypes, popTypeKey);
}

export function subjectTypeName(subjectTypeKey: string): string {
  return lookup(names.subjectTypes, subjectTypeKey);
}
