// Client loading interface for the static Encyclopedia data generated by
// tools/encyclopedia-scraping/ into public/encyclopedia/ (contracts/
// encyclopedia-data-contract.md). No component fetches those JSON files
// directly — this is the one seam, so the on-disk layout can change
// without touching every consumer. Type-only import from the generation
// tool's shared types (data-model.md is the source of truth for both).
import type {
  EncyclopediaEntry,
  Manifest,
  SearchIndexRow,
} from "../../../tools/encyclopedia-scraping/types";

const BASE_PATH = "/encyclopedia";

let manifestPromise: Promise<Manifest> | undefined;
let searchIndexPromise: Promise<SearchIndexRow[]> | undefined;
const categoryCache = new Map<string, Promise<EncyclopediaEntry[]>>();

async function fetchJson<T>(path: string): Promise<T> {
  const response = await fetch(path);
  if (!response.ok) {
    throw new Error(`Encyclopedia data fetch failed: ${path} (${response.status})`);
  }
  return response.json() as Promise<T>;
}

export function loadManifest(): Promise<Manifest> {
  manifestPromise ??= fetchJson<Manifest>(`${BASE_PATH}/manifest.json`);
  return manifestPromise;
}

export function loadSearchIndex(): Promise<SearchIndexRow[]> {
  searchIndexPromise ??= fetchJson<SearchIndexRow[]>(`${BASE_PATH}/search-index.json`);
  return searchIndexPromise;
}

/** Fetches and caches one category's entries — repeated calls for the
 * same category resolve from the in-memory cache, never re-fetch. */
export function loadCategory(categoryId: string): Promise<EncyclopediaEntry[]> {
  let cached = categoryCache.get(categoryId);
  if (!cached) {
    cached = fetchJson<EncyclopediaEntry[]>(`${BASE_PATH}/${categoryId}.json`);
    categoryCache.set(categoryId, cached);
  }
  return cached;
}

/** Finds one entry by key within an already-loaded category's entries —
 * a component never has to fetch a category just to render a plain-text
 * fallback for a cross-reference it already knows is unresolved. */
export function findEntry(entries: EncyclopediaEntry[], key: string): EncyclopediaEntry | undefined {
  return entries.find((entry) => entry.key === key);
}
