// Every confirmed source contributing to the 5 computed Army Stats this
// feature needs: `discipline`, `military_tactics` (displayed "Tactics"),
// `fort_limit_modifier`, `siege_ability`, and `global_defensive`
// (displayed "Fort Defense" — NOT the literal string "fort_defense",
// which does not exist as an internal keyword; confirmed via
// game/in_game/gui/military_ledger.gui and
// main_menu/localization/english/modifier_types_l_english.yml — see
// specs/012-firepower-tab/research.md §5).
//
// Generated by tools/firepower-reference/generate-modifier-sources.ts,
// which recursively scans every .txt file under the game's advances/,
// government_reforms/, estate_privileges/, laws/, societal_values/,
// auto_modifiers/, religions/, religious_aspects/, subject_types/,
// chivalric_orders/, international_organizations/, gods/, avatars/, and
// bureaucracies/ directories for any of the 5 stat keywords, rather than
// a hand-transcribed list (too error-prone across 60+ files touching
// `global_defensive` alone). Paradox script "@name = value" file-local
// constants (e.g. `fort_limit_modifier = @fort_limit_modifier_increase`
// in advances/3_fort_level.txt) are resolved to their real numeric value.
// Law files nest one extra level (category -> choice id) versus every
// other category; `sourceName` for a `law` entry is the CHOICE id (e.g.
// `expanded_levies_policy`), matching the save's `nation_laws.object`
// shape, never the law category id (`recruitment_law`) itself.
//
// `sourceKind: 'dynamic'` marks a source whose value scales with runtime
// game state this feature doesn't otherwise parse (e.g. army_tradition-
// or horde_unity-scaled auto_modifiers) — its `value` is still the flat
// number found in the definition file (useful for reference/display) but
// callers computing a country's total for one of the 5 stats MUST NOT
// include `dynamic` entries in that sum, since correctly applying them
// needs state (horde unity, karma, population ratios, army tradition
// brackets) this feature does not parse.
//
// `sourceKind: 'other'` entries (religions, religious_aspects,
// subject_types, chivalric_orders, international_organizations, gods,
// avatars, bureaucracies) are catalogued for completeness but are NOT
// currently joined against any per-country save data by this feature —
// only 'advance'/'reform'/'privilege'/'law' sources are summed into a
// country's Army Stats totals (armyNavyStats.ts). Treat 'other' as a
// documented reference catalog for possible future use, not a ready-to-
// join source list.
//
// Character/leader trait contributions to discipline/military_tactics/
// siege_ability are NOT captured here at all — no traits/*.txt files are
// scanned, since this codebase has no character/leader parsing. This is
// an intentional, accepted gap (specs/012-firepower-tab/spec.md
// Assumptions — the resulting total is a documented partial, not a bug).
//
// Regenerate the same way if a future game version adds/changes a
// source: re-run generate-modifier-sources.ts against an updated install
// and replace this file's contents.
export type ModifierStat = "discipline" | "military_tactics" | "fort_limit_modifier" | "siege_ability" | "global_defensive";
export type ModifierSourceKind = "advance" | "reform" | "privilege" | "law" | "societal_value" | "other" | "dynamic";

export interface ModifierSourceEntry {
  sourceKind: ModifierSourceKind;
  sourceName: string;
  stat: ModifierStat;
  value: number | null; // null for 'dynamic' entries (runtime-state-scaled or conditional, not a flat value)
  note?: string;
}

export const MILITARY_MODIFIER_REFERENCE: ModifierSourceEntry[] = [
  {
    "sourceKind": "advance",
    "sourceName": "a_neverending_crusade",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_KNI.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "ant_the_eternal_resistance",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_albanian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "aqu_friulian_soldiery",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_group_rhaetian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "auftragstaktik",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_pru.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "bul_the_standing_drilled_infantry",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_BUL.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "cli_the_windic_march_arsenal",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_slovene.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "conquerors_legacy",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_TIM.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "cossack_administration",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/estate_cossacks.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "dal_the_soldato_dalmantine",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_dalmatian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "discipline_drills",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/4_choices_mil.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "feo_the_gothic_red_guard_advance",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_group_greek.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "french_ambition",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_FRA.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "hum_the_kosaca_iron_fist",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_SER.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "ira_the_qurchi",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_IRA.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "jap_bushido",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_japan.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "lat_the_new_praetorian_guard_advance",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/frankokratia.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "mandinka_warrior_spirit",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_MAL.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "military_border",
    "stat": "discipline",
    "value": 0.03,
    "note": "in_game/common/advances/country_HAB.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "mod_accademia_militare",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_emilian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "modernization_of_the_military",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_SON.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "nav_basque_ferocity",
    "stat": "discipline",
    "value": 0.025,
    "note": "in_game/common/advances/country_NAV.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "ori_odia_militarization",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_ori.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pcz_piacentine_soldiery",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_emilian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pea_the_griffin_companies",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_median.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pie_ordinanza_piedmontese",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_piedmontese.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pis_natural_philosophy",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_tuscan.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pun_reforming_the_punjabi_army",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_punjabi.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "raj_mandatory_firearm_drilling",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_rajasthani.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "rav_battle_of_ravenna",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_romagnol.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "reform_the_feudal_army",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_BUR.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "rom_restore_the_legions",
    "stat": "discipline",
    "value": 0.025,
    "note": "in_game/common/advances/country_ROM.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "royal_mamluks",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_mam.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "seljuk_roots",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/beyliks.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "sia_thai_unity",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_sia.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "smz_tsurinobuse",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/japanese_unique.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "svn_the_slavonian_grenadier_regiments",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_cro.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "swedish_steel",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_SWE.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "teu_crusader_discipline",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_TEU.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "turkic_traditions",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_TUR.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "wallachian_heritage",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_group_romanian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "warriors_unity",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/culture_haudenosaunee.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "zmw_discipline_and_traning",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/advances/country_zmw.txt"
  },
  {
    "sourceKind": "dynamic",
    "sourceName": "high_horde_unity",
    "stat": "discipline",
    "value": 0.1,
    "note": "in_game/common/auto_modifiers/country.txt"
  },
  {
    "sourceKind": "dynamic",
    "sourceName": "low_karma",
    "stat": "discipline",
    "value": 0.025,
    "note": "in_game/common/auto_modifiers/country.txt"
  },
  {
    "sourceKind": "dynamic",
    "sourceName": "neutral_karma",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/auto_modifiers/country.txt"
  },
  {
    "sourceKind": "dynamic",
    "sourceName": "proper_culture_nobles_ratio",
    "stat": "discipline",
    "value": 0.1,
    "note": "in_game/common/auto_modifiers/country.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "al_mamalik_al_sultaniyya",
    "stat": "discipline",
    "value": 0.025,
    "note": "in_game/common/laws/01_military_laws.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "apc_senapati_focus_policy",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/laws/02_country_specific.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "black_army_policy",
    "stat": "discipline",
    "value": 0.025,
    "note": "in_game/common/laws/01_military_laws.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "byz_tagmata_policy_upgraded",
    "stat": "discipline",
    "value": 0.025,
    "note": "in_game/common/laws/01_military_laws.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "elite_training_policy",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/laws/01_military_laws.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "miri_piri",
    "stat": "discipline",
    "value": 0.025,
    "note": "in_game/common/laws/sikhism.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "sump_law_warrior_culture",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/laws/02_country_specific.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "ares_god",
    "stat": "discipline",
    "value": 0.1,
    "note": "in_game/common/gods/hellenism.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "calvinist",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/religions/christian.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "march",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/subject_types/march.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "pradhana_maha_samanta",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/subject_types/samanta.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "shakti_god",
    "stat": "discipline",
    "value": 0.03,
    "note": "in_game/common/gods/hindu.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "tyr_god",
    "stat": "discipline",
    "value": 0.01,
    "note": "in_game/common/gods/norse.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "war_god",
    "stat": "discipline",
    "value": 0.01,
    "note": "in_game/common/gods/folk_default.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "worship_war_god",
    "stat": "discipline",
    "value": 0.01,
    "note": "in_game/common/religious_aspects/folk_default.txt"
  },
  {
    "sourceKind": "privilege",
    "sourceName": "clergy_military_orders",
    "stat": "discipline",
    "value": 0.025,
    "note": "in_game/common/estate_privileges/clergy_estate.txt"
  },
  {
    "sourceKind": "privilege",
    "sourceName": "primacy_of_nobility",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/estate_privileges/nobles_estate.txt"
  },
  {
    "sourceKind": "privilege",
    "sourceName": "rajput_society",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/estate_privileges/nobles_estate.txt"
  },
  {
    "sourceKind": "reform",
    "sourceName": "diwan_i_bandagan",
    "stat": "discipline",
    "value": 0.025,
    "note": "in_game/common/government_reforms/country_specific.txt"
  },
  {
    "sourceKind": "reform",
    "sourceName": "modern_imperial_army",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/government_reforms/country_specific.txt"
  },
  {
    "sourceKind": "reform",
    "sourceName": "weapons_quality_standards",
    "stat": "discipline",
    "value": 0.05,
    "note": "in_game/common/government_reforms/common.txt"
  },
  {
    "sourceKind": "societal_value",
    "sourceName": "aristocracy_vs_plutocracy",
    "stat": "discipline",
    "value": 0.1,
    "note": "in_game/common/societal_values/00_default.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "a_fortified_border",
    "stat": "fort_limit_modifier",
    "value": 0.2,
    "note": "in_game/common/advances/country_NED.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "crt_the_cretan_labyrinth_of_fortifications_advance",
    "stat": "fort_limit_modifier",
    "value": 0.25,
    "note": "in_game/common/advances/frankokratia.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "fort_limit_1_advance",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/3_fort_level.txt (resolved from @fort_limit_modifier_increase)"
  },
  {
    "sourceKind": "advance",
    "sourceName": "fort_limit_2_advance",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/3_fort_level.txt (resolved from @fort_limit_modifier_increase)"
  },
  {
    "sourceKind": "advance",
    "sourceName": "fort_limit_3_advance",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/3_fort_level.txt (resolved from @fort_limit_modifier_increase)"
  },
  {
    "sourceKind": "advance",
    "sourceName": "fort_limit_4_advance",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/3_fort_level.txt (resolved from @fort_limit_modifier_increase)"
  },
  {
    "sourceKind": "advance",
    "sourceName": "fort_limit_5_advance",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/3_fort_level.txt (resolved from @fort_limit_modifier_increase)"
  },
  {
    "sourceKind": "advance",
    "sourceName": "fort_limit_6_advance",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/3_fort_level.txt (resolved from @fort_limit_modifier_increase)"
  },
  {
    "sourceKind": "advance",
    "sourceName": "fortress_of_the_balkans",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/country_BUL.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "kor_fortresses_of_goguryeo",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/country_KOR.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "LIV_crusader_forts",
    "stat": "fort_limit_modifier",
    "value": 0.2,
    "note": "in_game/common/advances/country_LIV.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "mfa_the_casale_citadel",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/culture_piedmontese.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "moe_the_hexamilion_modernization_advance",
    "stat": "fort_limit_modifier",
    "value": 0.2,
    "note": "in_game/common/advances/culture_group_greek.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pal_protection_of_exclaves",
    "stat": "fort_limit_modifier",
    "value": 0.2,
    "note": "in_game/common/advances/country_pal.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pie_citadel_system",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/culture_piedmontese.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "romagnol_mura_malatestiani",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/culture_romagnol.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "sal_the_alpine_strongholds",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/culture_vivaro_alpine.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "sic_naval_vigilance",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/culture_sicilian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "spl_duchy_of_spoleto",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/culture_median.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "teu_expanded_marches",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/country_TEU.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "tro_the_defensive_network_of_klobuk",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/advances/country_SER.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "vauban_fortifications",
    "stat": "fort_limit_modifier",
    "value": 0.2,
    "note": "in_game/common/advances/country_FRA.txt"
  },
  {
    "sourceKind": "privilege",
    "sourceName": "noble_fortification_licenses",
    "stat": "fort_limit_modifier",
    "value": 0.1,
    "note": "in_game/common/estate_privileges/nobles_estate.txt"
  },
  {
    "sourceKind": "reform",
    "sourceName": "military_order_reform",
    "stat": "fort_limit_modifier",
    "value": 0.25,
    "note": "in_game/common/government_reforms/theocracy.txt"
  },
  {
    "sourceKind": "societal_value",
    "sourceName": "offensive_vs_defensive",
    "stat": "fort_limit_modifier",
    "value": 0.5,
    "note": "in_game/common/societal_values/00_default.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "a_fortified_border",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/country_NED.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "ahimsa",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/religion_buddhist.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "albanian_the_fortified_kulla_houses",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/culture_albanian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "alpine_defensiveness",
    "stat": "global_defensive",
    "value": 0.25,
    "note": "in_game/common/advances/culture_high_alemannic.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "arduous_terrain",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/region_asia.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "arg_the_gibraltar_of_the_levant_advance",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/frankokratia.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "cel_defensive",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_irish.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "cep_ionian_sea_wall_advance",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/frankokratia.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "cir_city_and_fortress",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_cir.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "consolidate_italian_holdings",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/culture_venetian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "defenses_of_novgorod",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_NOV.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "defensive_mentality",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/4_choices_mil.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "emilian_the_tera_cruda",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_emilian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "feo_the_bastion_of_mangup_advance",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/culture_group_greek.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "flo_florentine_bastions",
    "stat": "global_defensive",
    "value": 0.15,
    "note": "in_game/common/advances/culture_tuscan.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "fortified_towns",
    "stat": "global_defensive",
    "value": 0.05,
    "note": "in_game/common/advances/country_BOH.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "fortress_of_the_balkans",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_BUL.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "geo_georgian_highlands",
    "stat": "global_defensive",
    "value": 0.25,
    "note": "in_game/common/advances/culture_georgian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "independence_from_mali",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/country_SON.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "isolated_reaches",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/religion_miaphysite.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "ita_enduring_hardship",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_ITA.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "kor_fortresses_of_goguryeo",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/country_KOR.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "legacy_of_breton_independence",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_BRI.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "lor_fortified_cities",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/country_lor.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "lords_of_the_rhone_corridor",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_PRO.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "luc_the_city_walls",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_tuscan.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "mai_garrison_of_the_rhine",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_mai.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "maltese_the_rahal_watch",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_sicilian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "median_bastioni_e_rocche",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_median.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "mhr_forts_of_maharashtra",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/culture_marathi.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "mountain_cities",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/region_north_america.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "neo_neopatras_fortresses_advance",
    "stat": "global_defensive",
    "value": 0.05,
    "note": "in_game/common/advances/frankokratia.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "nine_garrisons_of_the_great_wall",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/country_chi.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "oda_influential_strongholds",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/japanese_unique.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "ogs_shinano_shugo",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/japanese_unique.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "piedmontese_the_piassafort",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_piedmontese.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "piedmontese_the_ricet",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_piedmontese.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "ple_pale_defenseworks_advance",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_irish.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "por_royal_military_academy",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_POR.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "raj_fortress_architecture",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_rajasthani.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "romagnol_mura_malatestiani",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_romagnol.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "slo_the_slovak_castle_system",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_slovak.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "slovene_the_tabor_defense_system",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/culture_slovene.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "sme_fortresses_of_samtskhe",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/country_sme.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "tra_the_vauban_transylvanian_bastion_synthesis",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/culture_group_romanian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "tre_pontic_trail_mastery",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_tre.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "tro_the_defensive_network_of_klobuk",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/advances/country_SER.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "ymn_isolated_heartland",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/advances/japanese_unique.txt"
  },
  {
    "sourceKind": "dynamic",
    "sourceName": "over_fort_limit",
    "stat": "global_defensive",
    "value": -1,
    "note": "in_game/common/auto_modifiers/country.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "defensive_stance",
    "stat": "global_defensive",
    "value": 0.25,
    "note": "in_game/common/laws/02_country_specific.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "defensive_stance_policy",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/laws/01_military_laws.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "frontier_maintained",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/laws/10_reforms_from_events.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "frontier_not_maintained",
    "stat": "global_defensive",
    "value": -0.1,
    "note": "in_game/common/laws/10_reforms_from_events.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "not_maintained",
    "stat": "global_defensive",
    "value": -0.1,
    "note": "in_game/common/laws/10_reforms_from_events.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "offensive_stance",
    "stat": "global_defensive",
    "value": -0.5,
    "note": "in_game/common/laws/02_country_specific.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "protection_principle",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/laws/00_republic.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "safeguard_holy_sites_policy",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/laws/00_theocracies.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "vegvar_system",
    "stat": "global_defensive",
    "value": 0.33,
    "note": "in_game/common/laws/10_reforms_from_events.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "ares_god",
    "stat": "global_defensive",
    "value": 0.25,
    "note": "in_game/common/gods/hellenism.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "durga_avatar",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/avatars/hindu.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "hermes_god",
    "stat": "global_defensive",
    "value": 0.25,
    "note": "in_game/common/gods/hellenism.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "karachay_balkar_paganism",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/religions/folk_european.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "kurma_avatar",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/avatars/hindu.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "lezgin_paganism",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/religions/folk_european.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "lordship_of_ireland",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/international_organizations/lordship_of_ireland.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "mandeaism",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/religions/mandean.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "march",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/subject_types/march.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "mari_paganism",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/religions/folk_european.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "order_of_the_dragon",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/chivalric_orders/01_historical_orders.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "pradhana_maha_samanta",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/subject_types/samanta.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "society_elephant_tyrol",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/chivalric_orders/02_german_societies.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "themata_bureaucracy",
    "stat": "global_defensive",
    "value": 0.2,
    "note": "in_game/common/bureaucracies/byz.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "tor_god",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/gods/norse.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "vainakh_paganism",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/religions/folk_european.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "vishnu_god",
    "stat": "global_defensive",
    "value": 0.05,
    "note": "in_game/common/gods/hindu.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "votian_religion",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/religions/folk_european.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "worship_tor_god",
    "stat": "global_defensive",
    "value": 0.25,
    "note": "in_game/common/religious_aspects/norse.txt"
  },
  {
    "sourceKind": "privilege",
    "sourceName": "shooting_societies",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/estate_privileges/burghers_estate.txt"
  },
  {
    "sourceKind": "privilege",
    "sourceName": "tribes_manrent",
    "stat": "global_defensive",
    "value": 0.1,
    "note": "in_game/common/estate_privileges/tribes_estate.txt"
  },
  {
    "sourceKind": "privilege",
    "sourceName": "vlastele_krayishnik",
    "stat": "global_defensive",
    "value": 0.15,
    "note": "in_game/common/estate_privileges/nobles_estate.txt"
  },
  {
    "sourceKind": "societal_value",
    "sourceName": "offensive_vs_defensive",
    "stat": "global_defensive",
    "value": -0.5,
    "note": "in_game/common/societal_values/00_default.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "adapted_incan_army",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/country_INC.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "alpine_defensiveness",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/culture_high_alemannic.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "austrian_military_flexibility",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/country_HAB.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "bavarian_hofkriegsrat",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/country_ubv.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "by_the_grace_of_god",
    "stat": "military_tactics",
    "value": 0.025,
    "note": "in_game/common/advances/government_theocracy.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "feudalism_advance",
    "stat": "military_tactics",
    "value": 1,
    "note": "in_game/common/advances/0_age_of_traditions.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "gunpowder_advance",
    "stat": "military_tactics",
    "value": 0.25,
    "note": "in_game/common/advances/0_age_of_renaissance.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "line_infantry",
    "stat": "military_tactics",
    "value": 0.25,
    "note": "in_game/common/advances/0_age_of_absolutism.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "military_tactics_advance_6",
    "stat": "military_tactics",
    "value": 0.25,
    "note": "in_game/common/advances/0_age_of_revolutions.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "perpetual_general_captain_of_the_people",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/culture_venetian.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pie_cavalleria_piemontese",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/culture_piedmontese.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pike_square",
    "stat": "military_tactics",
    "value": 0.25,
    "note": "in_game/common/advances/0_age_of_discovery.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "pis_natural_philosophy",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/culture_tuscan.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "preobrazhensky_semyonovsky_imperial_guard",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/country_MOS.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "spanish_square",
    "stat": "military_tactics",
    "value": 0.25,
    "note": "in_game/common/advances/0_age_of_reformation.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "tamerlane_chess",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/country_TIM.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "urb_the_hill_fortresses",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/culture_romagnol.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "vivaro_alpine_infantry",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/culture_vivaro_alpine.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "zmw_cow_horn_tactics",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/advances/country_zmw.txt"
  },
  {
    "sourceKind": "dynamic",
    "sourceName": "country_base_values",
    "stat": "military_tactics",
    "value": 1,
    "note": "in_game/common/auto_modifiers/country.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "meritocratic_leadership_policy",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/laws/01_military_laws.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "noble_cadets_policy",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/laws/01_military_laws.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "conquistador",
    "stat": "military_tactics",
    "value": 0.5,
    "note": "in_game/common/subject_types/conquistador.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "magister_militum_bureaucracy",
    "stat": "military_tactics",
    "value": 0.2,
    "note": "in_game/common/bureaucracies/byz.txt"
  },
  {
    "sourceKind": "other",
    "sourceName": "war_council_bureaucracy",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/bureaucracies/generic.txt"
  },
  {
    "sourceKind": "privilege",
    "sourceName": "cossacks_register",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/estate_privileges/cossacks_estate.txt"
  },
  {
    "sourceKind": "reform",
    "sourceName": "european_militia_reform",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/government_reforms/country_specific.txt"
  },
  {
    "sourceKind": "reform",
    "sourceName": "ottoman_new_order_army",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/government_reforms/country_specific.txt"
  },
  {
    "sourceKind": "societal_value",
    "sourceName": "quality_vs_quantity",
    "stat": "military_tactics",
    "value": 0.1,
    "note": "in_game/common/societal_values/00_default.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "chinese_siege_engineers",
    "stat": "siege_ability",
    "value": 0.1,
    "note": "in_game/common/advances/culture_group_chinese.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "engineer_corps",
    "stat": "siege_ability",
    "value": 0.2,
    "note": "in_game/common/advances/4_choices_mil.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "kbo_permanent_sieges",
    "stat": "siege_ability",
    "value": 0.1,
    "note": "in_game/common/advances/country_KBO.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "shadow_of_ambition",
    "stat": "siege_ability",
    "value": 0.1,
    "note": "in_game/common/advances/country_MCH.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "siege_ability_revolutions",
    "stat": "siege_ability",
    "value": 0.2,
    "note": "in_game/common/advances/0_age_of_revolutions.txt"
  },
  {
    "sourceKind": "advance",
    "sourceName": "slovak_the_slovak_sappers",
    "stat": "siege_ability",
    "value": 0.15,
    "note": "in_game/common/advances/culture_slovak.txt"
  },
  {
    "sourceKind": "dynamic",
    "sourceName": "army_tradition",
    "stat": "siege_ability",
    "value": 0.1,
    "note": "in_game/common/auto_modifiers/country.txt"
  },
  {
    "sourceKind": "law",
    "sourceName": "offensive_stance",
    "stat": "siege_ability",
    "value": 0.05,
    "note": "in_game/common/laws/02_country_specific.txt"
  },
  {
    "sourceKind": "reform",
    "sourceName": "horse_artillery",
    "stat": "siege_ability",
    "value": 0.1,
    "note": "in_game/common/government_reforms/common.txt"
  },
  {
    "sourceKind": "societal_value",
    "sourceName": "offensive_vs_defensive",
    "stat": "siege_ability",
    "value": 0.1,
    "note": "in_game/common/societal_values/00_default.txt"
  }
];

