// Post-ship, 2026-09-21 (Ruler History, explicit user request): real
// ruler names, not "Ruler #N". `rulerNames.json` is generated by
// tools/ruler-names-scraping/generate.ts from the game's own install
// (`npm run generate:ruler-names -- --install <path>`) — the same
// key-lookup-from-game-files pattern 008's Encyclopedia already uses
// for game_concepts. A save's `character_db.*.first_name` is a raw key
// into this table (e.g. "name_birger"), never display text itself.
import rulerNamesJson from "./rulerNames.json";

const RULER_NAMES = rulerNamesJson as Record<string, string>;

/** Resolves a character's `first_name` localization key to its real
 * English name, or `null` if the key is missing or unresolvable (never
 * a guessed/fabricated name — constitution Principle IV). Callers fall
 * back to a neutral label (e.g. a regnal number) when this returns
 * `null`. */
export function resolveRulerFirstName(firstNameKey: string | null): string | null {
  if (firstNameKey === null) return null;
  return RULER_NAMES[firstNameKey] ?? null;
}
