// The Firepower tab's unit-type → category/age/levy lookup, sourced
// directly from the game's own files (constitution Principle IV) rather
// than a guessed pattern.
//
// Every concrete unit type in `game/in_game/common/unit_types/*.txt`
// (excluding the two abstract age-template files and readme.txt)
// declares, directly or via a `copy_from` chain resolved back to an
// abstract `age_N_..._<category>` template, a `category` and an `age`
// (`age_1_traditions`..`age_6_revolutions`, mapped here to 1-6); `levy`
// is read as an own field only (never inherited through copy_from — the
// abstract bases never declare it) and defaults to false when absent.
// EU5's raw category values are collapsed to the display categories the
// Firepower spec actually asks for: army_light_infantry/army_heavy_infantry
// → "Infantry", army_light_cavalry/army_heavy_cavalry → "Cavalry",
// army_artillery → "Artillery", army_auxiliary → "Supply";
// navy_heavy_ship → "Heavies", navy_light_ship → "Lights",
// navy_transport → "Transports", navy_galley → "Galleys". Both the raw
// EU5 category and the resolved display category are kept.
//
// specs/012-firepower-tab research.md §3. Static game-reference data,
// not derivable from a save at runtime (the browser has no access to a
// user's local game install) — regenerate with
// `npx tsx tools/firepower-reference/generate-unit-types.ts --install <path>`
// if a future game version adds/renames/recategorizes a unit type.
export interface UnitTypeReferenceEntry {
  /** Raw EU5 category, e.g. 'army_heavy_cavalry'. */
  category: string;
  displayCategory: "Infantry" | "Cavalry" | "Artillery" | "Supply" | "Heavies" | "Lights" | "Transports" | "Galleys";
  age: 1 | 2 | 3 | 4 | 5 | 6;
  isLevy: boolean;
}

export const UNIT_TYPE_REFERENCE: Record<string, UnitTypeReferenceEntry> = {
  "a_a_urughs": { category: "army_auxiliary", displayCategory: "Supply", age: 1, isLevy: false },
  "a_absolutism_cawa": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_absolutism_janissaries": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_akinji": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 3, isLevy: false },
  "a_akritai": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_almogavars": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_archers": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_armored_horsemen": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_arquebusiers": { category: "army_light_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_austrian_grenzer": { category: "army_light_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_austrian_grenzhussar": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 6, isLevy: false },
  "a_baggage_train": { category: "army_auxiliary", displayCategory: "Supply", age: 4, isLevy: false },
  "a_banner_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 4, isLevy: false },
  "a_bavarian_jager": { category: "army_light_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_bedouin_cavalry": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_bengali_elephant_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_black_guard": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_byz_helepolis_cannon_unit": { category: "army_artillery", displayCategory: "Artillery", age: 4, isLevy: false },
  "a_byzantine_cataphracts": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_byzantine_cataphracts_2": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_byzantine_cataphracts_3": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 3, isLevy: false },
  "a_byzantine_cataphracts_4": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 4, isLevy: false },
  "a_byzantine_cataphracts_5": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 5, isLevy: false },
  "a_byzantine_cataphracts_6": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 6, isLevy: false },
  "a_cacadores": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_camp_followers": { category: "army_auxiliary", displayCategory: "Supply", age: 1, isLevy: false },
  "a_caroleans": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_catalan_crossbowmen": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_caterans": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_cavaliers": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 3, isLevy: true },
  "a_cavalrymen": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_cawa": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_cetbang_cannon": { category: "army_artillery", displayCategory: "Artillery", age: 3, isLevy: false },
  "a_chambered_cannon": { category: "army_artillery", displayCategory: "Artillery", age: 4, isLevy: false },
  "a_champions": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_chieftains": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_clan_retainer_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_clan_retainers": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_conscripts": { category: "army_light_infantry", displayCategory: "Infantry", age: 6, isLevy: true },
  "a_crossbowmen": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_crusader_knights": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_crusader_knights_base": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_crusader_knights_levy": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_cuirassiers": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 6, isLevy: false },
  "a_dahomey_amazons": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_discovery_cawa": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_discovery_conquistadors": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_discovery_janissaries": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_discovery_qizilbash": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 3, isLevy: false },
  "a_eagle_warrior": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_early_arquebusiers": { category: "army_light_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_early_longbowmen": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_early_paik": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_early_paik_infantry": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_esho_cavalry_oyo": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 3, isLevy: false },
  "a_experimental_riflemen": { category: "army_light_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_falconet": { category: "army_artillery", displayCategory: "Artillery", age: 3, isLevy: false },
  "a_farari_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_farari_infantry": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_feudal_levy": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_flintlock_levy": { category: "army_light_infantry", displayCategory: "Infantry", age: 4, isLevy: true },
  "a_florentine_citizen_militia": { category: "army_light_infantry", displayCategory: "Infantry", age: 3, isLevy: true },
  "a_flying_battery": { category: "army_artillery", displayCategory: "Artillery", age: 6, isLevy: false },
  "a_footmen": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_footmen_levy": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_fusiliers": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_gallop_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 5, isLevy: false },
  "a_gallowglass": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_gebirgsschutzen_infantry": { category: "army_light_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_gendarmerie": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 6, isLevy: true },
  "a_genoese_crossbowmen": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_ghilman": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_greek_fire_discovery_infantry": { category: "army_light_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_greek_fire_renaissance_infantry": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_grenadiers": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_gurkha": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_hajduk": { category: "army_light_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_hakkapelitta": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 5, isLevy: false },
  "a_halberdiers": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_halqah_unit": { category: "army_auxiliary", displayCategory: "Supply", age: 1, isLevy: false },
  "a_handgonners": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_heavy_cavalrymen": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_heavy_lancers": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 4, isLevy: false },
  "a_hesse_jager": { category: "army_light_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_hobelars": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_horsemen": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_houfnice": { category: "army_artillery", displayCategory: "Artillery", age: 2, isLevy: false },
  "a_hungarian_hussars": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 4, isLevy: false },
  "a_hunters": { category: "army_light_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_hussars": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 5, isLevy: false },
  "a_hwacha": { category: "army_artillery", displayCategory: "Artillery", age: 2, isLevy: false },
  "a_indian_elephant_auxiliary": { category: "army_auxiliary", displayCategory: "Supply", age: 1, isLevy: false },
  "a_indian_elephant_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_iron_helmet_musketeers": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_iron_pagoda_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_jaguar_warrior": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_jazayerchi": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_jonow_auxiliary": { category: "army_auxiliary", displayCategory: "Supply", age: 1, isLevy: false },
  "a_kerns": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_khmer_ballista_elephant_infantry": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_lancers": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 3, isLevy: false },
  "a_landsknechte": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_lanzas_de_castilla": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 3, isLevy: false },
  "a_late_almogavars": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: true },
  "a_late_cavaliers": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 4, isLevy: true },
  "a_late_crusader_knights": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_late_crusader_knights_base": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_late_crusader_knights_levy": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: true },
  "a_late_gallowglass": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: true },
  "a_late_karambit_warrior": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_late_longbowmen": { category: "army_light_infantry", displayCategory: "Infantry", age: 3, isLevy: true },
  "a_late_paik": { category: "army_light_infantry", displayCategory: "Infantry", age: 5, isLevy: true },
  "a_late_paik_infantry": { category: "army_light_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_late_winged_hussars": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 5, isLevy: false },
  "a_legionaries_1": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_legionaries_2": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_legionaries_3": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_legionaries_4": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_legionaries_5": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_legionaries_6": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_light_dragoons": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 6, isLevy: false },
  "a_light_jurchen_cavalry": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_light_lancers": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 3, isLevy: false },
  "a_lodge_warriors": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_logistics_corps": { category: "army_auxiliary", displayCategory: "Supply", age: 6, isLevy: false },
  "a_longbowmen": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: true },
  "a_lour_lances": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_mailed_knights": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: true },
  "a_mamluk_horsemen_renaissance": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_mamluk_horsemen_traditions": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_mamluk_unit_renaissance": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_mamluk_unit_traditions": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_mandekalu_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_mandekalu_infantry": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_matchlock_levy": { category: "army_light_infantry", displayCategory: "Infantry", age: 3, isLevy: true },
  "a_mauricians": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_men_at_arms": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_men_at_arms_levy": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: true },
  "a_militiamen": { category: "army_light_infantry", displayCategory: "Infantry", age: 5, isLevy: true },
  "a_moa_hunters": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_musketeers": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_muslim_riders_vijay": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_naft_throwers": { category: "army_light_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_noble_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: true },
  "a_order_knights": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_order_knights_2": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_orissan_elephant_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_paik": { category: "army_light_infantry", displayCategory: "Infantry", age: 3, isLevy: true },
  "a_paik_infantry": { category: "army_light_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_pandur": { category: "army_light_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_peasant_levy": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: true },
  "a_pikemen": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_pistoleers": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 4, isLevy: false },
  "a_plated_knights": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 2, isLevy: true },
  "a_pontifical_swiss_guard": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_provincial_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 5, isLevy: true },
  "a_prussian_grenadiers": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_red_cannon": { category: "army_artillery", displayCategory: "Artillery", age: 4, isLevy: false },
  "a_redcoats": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_reformation_cawa": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_reformation_janissaries": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_reformation_qizilbash": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 4, isLevy: false },
  "a_reformed_gallowglass": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: true },
  "a_reislaufer": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_renaissance_cawa": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_renaissance_conquistadors": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_renaissance_janissaries": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_revolutions_cawa": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_revolutions_janissaries": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_royal_mortar": { category: "army_artillery", displayCategory: "Artillery", age: 5, isLevy: false },
  "a_saxon_defensioner": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_schiltron": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_scottish_highlander": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: true },
  "a_serbian_hussars": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_sharpshooters": { category: "army_light_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_siamese_advanced_elephant_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 4, isLevy: false },
  "a_sofa_infantry": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_sowar_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 4, isLevy: false },
  "a_steppe_horde": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 1, isLevy: true },
  "a_steppe_horse_archers": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 1, isLevy: false },
  "a_supply_carts": { category: "army_auxiliary", displayCategory: "Supply", age: 2, isLevy: false },
  "a_supply_convoy": { category: "army_auxiliary", displayCategory: "Supply", age: 3, isLevy: false },
  "a_tercio": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_teulu": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 1, isLevy: true },
  "a_thai_elephant_cavalry": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 2, isLevy: false },
  "a_the_black_army": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_tofangchi": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_tribal_cavalry": { category: "army_light_cavalry", displayCategory: "Cavalry", age: 1, isLevy: true },
  "a_tribesmen": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_tupchi": { category: "army_artillery", displayCategory: "Artillery", age: 5, isLevy: false },
  "a_varangians": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: false },
  "a_varangians_2": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_varangians_3": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 3, isLevy: false },
  "a_varangians_4": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 4, isLevy: false },
  "a_varangians_5": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 5, isLevy: false },
  "a_varangians_6": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 6, isLevy: false },
  "a_villagers": { category: "army_light_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_wagenburg": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_wagon_train": { category: "army_auxiliary", displayCategory: "Supply", age: 5, isLevy: false },
  "a_war_party": { category: "army_light_infantry", displayCategory: "Infantry", age: 2, isLevy: false },
  "a_warriors": { category: "army_heavy_infantry", displayCategory: "Infantry", age: 1, isLevy: true },
  "a_winged_hussars": { category: "army_heavy_cavalry", displayCategory: "Cavalry", age: 4, isLevy: false },
  "n_archipelago_frigate": { category: "navy_galley", displayCategory: "Galleys", age: 6, isLevy: false },
  "n_atakebune": { category: "navy_galley", displayCategory: "Galleys", age: 4, isLevy: false },
  "n_baghlah": { category: "navy_light_ship", displayCategory: "Lights", age: 5, isLevy: false },
  "n_baochuan": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 3, isLevy: false },
  "n_barque": { category: "navy_light_ship", displayCategory: "Lights", age: 2, isLevy: false },
  "n_birlinn": { category: "navy_galley", displayCategory: "Galleys", age: 1, isLevy: true },
  "n_bomb_ketch": { category: "navy_light_ship", displayCategory: "Lights", age: 6, isLevy: false },
  "n_brig": { category: "navy_transport", displayCategory: "Transports", age: 4, isLevy: false },
  "n_cakradonya": { category: "navy_galley", displayCategory: "Galleys", age: 4, isLevy: false },
  "n_canoe": { category: "navy_galley", displayCategory: "Galleys", age: 1, isLevy: false },
  "n_caravel": { category: "navy_light_ship", displayCategory: "Lights", age: 3, isLevy: false },
  "n_carrack": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 3, isLevy: false },
  "n_catalan_galley": { category: "navy_galley", displayCategory: "Galleys", age: 1, isLevy: false },
  "n_cog": { category: "navy_transport", displayCategory: "Transports", age: 1, isLevy: false },
  "n_dhow": { category: "navy_light_ship", displayCategory: "Lights", age: 1, isLevy: false },
  "n_early_carrack": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 2, isLevy: false },
  "n_early_iberian_caravel": { category: "navy_light_ship", displayCategory: "Lights", age: 1, isLevy: false },
  "n_early_iberian_galleon": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 3, isLevy: false },
  "n_early_turtle_ship": { category: "navy_galley", displayCategory: "Galleys", age: 2, isLevy: false },
  "n_eastindiaman": { category: "navy_transport", displayCategory: "Transports", age: 6, isLevy: false },
  "n_fishing_boat": { category: "navy_transport", displayCategory: "Transports", age: 1, isLevy: true },
  "n_flute": { category: "navy_transport", displayCategory: "Transports", age: 3, isLevy: false },
  "n_frigate": { category: "navy_light_ship", displayCategory: "Lights", age: 5, isLevy: false },
  "n_galiot": { category: "navy_galley", displayCategory: "Galleys", age: 4, isLevy: false },
  "n_galleass": { category: "navy_galley", displayCategory: "Galleys", age: 4, isLevy: false },
  "n_galleon": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 4, isLevy: false },
  "n_genoese_galley": { category: "navy_galley", displayCategory: "Galleys", age: 1, isLevy: false },
  "n_greek_fire_galley_discovery": { category: "navy_galley", displayCategory: "Galleys", age: 3, isLevy: false },
  "n_greek_fire_galley_renaissance": { category: "navy_galley", displayCategory: "Galleys", age: 2, isLevy: false },
  "n_hanseatic_cog": { category: "navy_transport", displayCategory: "Transports", age: 1, isLevy: false },
  "n_heavy_frigate": { category: "navy_light_ship", displayCategory: "Lights", age: 6, isLevy: false },
  "n_hulk": { category: "navy_transport", displayCategory: "Transports", age: 2, isLevy: false },
  "n_iberian_caravel": { category: "navy_light_ship", displayCategory: "Lights", age: 2, isLevy: false },
  "n_iberian_galleon": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 4, isLevy: false },
  "n_italian_galleass": { category: "navy_galley", displayCategory: "Galleys", age: 4, isLevy: false },
  "n_jong": { category: "navy_light_ship", displayCategory: "Lights", age: 1, isLevy: false },
  "n_kabang": { category: "navy_transport", displayCategory: "Transports", age: 1, isLevy: false },
  "n_kilwan_dhow": { category: "navy_light_ship", displayCategory: "Lights", age: 2, isLevy: false },
  "n_kilwan_zambuc": { category: "navy_transport", displayCategory: "Transports", age: 2, isLevy: false },
  "n_long_fada": { category: "navy_galley", displayCategory: "Galleys", age: 1, isLevy: false },
  "n_long_fada_2": { category: "navy_galley", displayCategory: "Galleys", age: 2, isLevy: false },
  "n_madurese_gali": { category: "navy_galley", displayCategory: "Galleys", age: 4, isLevy: false },
  "n_mediterrannean_galley": { category: "navy_galley", displayCategory: "Galleys", age: 2, isLevy: false },
  "n_merchantman": { category: "navy_transport", displayCategory: "Transports", age: 5, isLevy: false },
  "n_mtepe": { category: "navy_light_ship", displayCategory: "Lights", age: 1, isLevy: false },
  "n_panokseon": { category: "navy_galley", displayCategory: "Galleys", age: 4, isLevy: false },
  "n_pinnace": { category: "navy_light_ship", displayCategory: "Lights", age: 4, isLevy: false },
  "n_sekibune": { category: "navy_galley", displayCategory: "Galleys", age: 3, isLevy: false },
  "n_ship_of_the_line": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 6, isLevy: false },
  "n_square_rigged_caravel": { category: "navy_light_ship", displayCategory: "Lights", age: 3, isLevy: false },
  "n_threedecker": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 6, isLevy: false },
  "n_traditional_galley": { category: "navy_galley", displayCategory: "Galleys", age: 1, isLevy: false },
  "n_turtle_ship": { category: "navy_galley", displayCategory: "Galleys", age: 4, isLevy: false },
  "n_twodecker": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 5, isLevy: false },
  "n_war_galleon": { category: "navy_heavy_ship", displayCategory: "Heavies", age: 4, isLevy: false },
  "n_war_galley": { category: "navy_galley", displayCategory: "Galleys", age: 3, isLevy: false },
  "n_xebec": { category: "navy_galley", displayCategory: "Galleys", age: 5, isLevy: false },
};
