// Generates src/battleSim/unknowns.ts from
// specs/019-battle-simulator/combat-unknowns.md so the result's
// Approximations panel always shows the ledger's own wording and status.
// Run: npx tsx tools/battle-sim-reference/generate-unknowns.ts
import { readFileSync, writeFileSync } from "node:fs";

const LEDGER = "specs/019-battle-simulator/combat-unknowns.md";
const OUT = "src/battleSim/unknowns.ts";

export function parseLedger(markdown: string): Record<string, { title: string; assumption: string; status: string }> {
  const out: Record<string, { title: string; assumption: string; status: string }> = {};
  for (const line of markdown.split("\n")) {
    const m = line.match(/^\| (U-\d{2}) \|(.*)\|\s*$/);
    if (!m) continue;
    const cells = m[2].split(" | ").map((c) => c.trim());
    // Columns: what we're unsure of | what we know | current assumption | resolve by | status
    const plain = (s: string) => s.replace(/\*\*/g, "").replace(/`/g, "");
    out[m[1]] = { title: plain(cells[0]), assumption: plain(cells[2]), status: cells[cells.length - 1] };
  }
  return out;
}

if (process.argv[1]?.endsWith("generate-unknowns.ts")) {
  const entries = parseLedger(readFileSync(LEDGER, "utf-8"));
  writeFileSync(
    OUT,
    [
      "// GENERATED by tools/battle-sim-reference/generate-unknowns.ts from",
      "// specs/019-battle-simulator/combat-unknowns.md — do not edit by hand.",
      "",
      "export interface CombatUnknown { title: string; assumption: string; status: string }",
      "",
      `export const COMBAT_UNKNOWNS: Record<string, CombatUnknown> = ${JSON.stringify(entries, null, 2)};`,
      "",
    ].join("\n"),
  );
  console.log(`Wrote ${OUT} (${Object.keys(entries).length} entries)`);
}
