// GENERATED by tools/battle-sim-reference/generate.ts — do not edit by hand.
// Combat constants and tables for the 019 battle simulator, extracted
// from the local EU5 install's own files (structured game-mechanics
// data only, per the constitution's Encyclopedia-data exception).
// Regenerate with
// `npx tsx tools/battle-sim-reference/generate.ts --install <EU5 game dir> [--game-version X]`.
// See specs/019-battle-simulator/research.md §1.

export interface TerrainEntry { defenderDice: number; frontageDelta: number }
export interface FormationSection { weights: Record<string, number>; maxFrontage: number | null }
export interface FormationEntry { isDefault: boolean; sections: Record<"left" | "center" | "right" | "reserves", FormationSection> }

export interface CombatRulesReference {
  gameVersion: string;
  nCombat: Record<string, number>;
  nUnit: Record<string, number>;
  baseFrontage: number;
  topography: Record<string, TerrainEntry>;
  vegetation: Record<string, TerrainEntry>;
  locationRanks: Record<string, { frontageDelta: number }>;
  formations: Record<string, FormationEntry>;
  generalTraits: Record<string, Partial<Record<string, number>>>;
}

export const COMBAT_RULES_REFERENCE: CombatRulesReference = {
  "gameVersion": "1.3.11",
  "nCombat": {
    "NAVAL_LEVY_IMPACT": 0.05,
    "RETREAT_STRENGTH_DAMAGE": 0.1,
    "GARRISON_AFTER_OCCUPATION": 0.01,
    "MORALE_COLLAPSE_THRESHOLD": 0.05,
    "MINIMUM_COMBAT_DURATION": 24,
    "MINIMUM_NAVAL_COMBAT_DURATION": 72,
    "NAVAL_LOW_MORALE_THRESHOLD": 1.5,
    "BOMBARD_BASE_CHANCE": 0.2,
    "BOMBARD_HOURS": 5,
    "HOURS_PER_PHASE": 5,
    "COMBAT_DICE_SIDE": 10,
    "COMBAT_BASE": 5,
    "COMBAT_MAX": 15,
    "COMBAT_DAMAGE_MULT": 0.01,
    "COMBAT_HOURLY_MORALE_TICK": 0.01,
    "COMBAT_IMPRISONED_UNIT_DEATH_RATE": 0.4,
    "STRAIT_CROSSING_DICE": -2,
    "RIVER_CROSSING_DICE": -1,
    "SEA_LANDING_DICE": -1,
    "FOOD_PERCENTAGE_LOST_AT_OCCUPATION": 0.9,
    "MAX_FRONTAGE_OVERSTACKING": 1.25,
    "LAND_LEVY_COMBAT_IMPACT": 0.75,
    "INITIATIVE_BASE_CHANCE": 0.1,
    "INITIATIVE_CHANCE_EACH": 0.02,
    "INITIATIVE_CHANCE_HOURS": 0.01,
    "INITIATIVE_CHANCE_MAX": 0.1,
    "COMBAT_SPEED_SCALE": 0.05,
    "NAVAL_EXPERIENCE_DAMAGE_REDUCTION": 0.5,
    "LAND_EXPERIENCE_DAMAGE_REDUCTION": 0.5,
    "LAND_STRENGTH_DAMAGE_MODIFIER": 0.2,
    "NAVAL_STRENGTH_DAMAGE_MODIFIER": 0.25,
    "LAND_MORALE_DAMAGE_MODIFIER": 1,
    "NAVAL_MORALE_DAMAGE_MODIFIER": 0.2,
    "NOT_ENGAGED_STRENGTH_DAMAGE_MODIFIER": 1.1,
    "NOT_ENGAGED_MORALE_DAMAGE_MODIFIER": 1.2,
    "NAVY_OVERRUN_EXTRA_CAPTURE_CHANCE": 0.15,
    "NAVAL_COMBAT_DAMAGED_SHIP_EXTRA_CAPTURE_SCALE": 0.025,
    "NAVAL_COMBAT_SHIP_STR_SINK_THRESHOLD": 0.1,
    "NAVAL_COMBAT_DAMAGED_SHIP_SINK_CHANCE": 10,
    "NAVAL_RETREAT_DAMAGE_THRESHOLD": 0.5,
    "NAVAL_RETREAT_CHANCE": 10,
    "BASE_MORALE_DAMAGE": 1,
    "FOOD_PERCENTAGE_LOST_AT_RETREAT": 0.5,
    "EXPERIENCE_GAIN": 30,
    "LAND_WAR_EXHAUSTION_FROM_LOSSES": 1,
    "NAVAL_WAR_EXHAUSTION_FROM_LOSSES": 1.5,
    "MAX_WAR_EXHAUSTION_FROM_BATTLE": 5,
    "TRADITION_GAIN_LAND": 10,
    "TRADITION_GAIN_NAVAL": 20,
    "PRESTIGE_VS_RIVAL": 1.5,
    "PRESTIGE_FROM_LAND": 0.5,
    "PRESTIGE_FROM_NAVAL": 0.5,
    "DAYS_PER_SIEGE_PHASE": 30,
    "MIN_DAYS_PER_SIEGE_PHASE": 7,
    "DAYS_PER_SIEGE_PHASE_WITHOUT_FORT": 15,
    "SIEGE_DISEASE_IMPACT": 0.05,
    "SIEGE_MAX_FORT_LIMIT_BONUS": 8,
    "SIEGE_REGIMENTS_FOR_ARTILLERY": 3,
    "SIEGE_MEMORY": 11,
    "SIEGE_WIN": 20,
    "MAX_BREACH": 3,
    "BREACH_REPAIR_PER_DAY": 0.01,
    "SIEGE_SUPPLY_SHORTAGE_LOSS": 0.02,
    "SIEGE_SUPPLY_SHORTAGE_IMPACT": 1,
    "SIEGE_FOOD_SHORTAGE_LOSS": 0.03,
    "SIEGE_FOOD_SHORTAGE_IMPACT": 2,
    "SIEGE_WATER_SHORTAGE_LOSS": 0.05,
    "SIEGE_WATER_SHORTAGE_IMPACT": 3,
    "SIEGE_DEFENDER_DESERTION_LOSS": 0.1,
    "SIEGE_DEFENDER_DESERTION_IMPACT": 2,
    "SIEGE_BREACH_LOSS": 0.05,
    "SIEGE_BREACH_IMPACT": 2,
    "SIEGE_DAYS_PER_PHASE": 5,
    "ASSAULT_ATTACKER_LOSS": 2.5,
    "ASSAULT_ATTACKER_MORALE_LOSS": 3,
    "ASSAULT_DEFENDER_LOSS": 0.03,
    "ASSAULT_DEFENDER_MORALE_LOSS": 0.3,
    "ASSAULT_DICE_MODIFIER": 5,
    "ASSAULT_WIDTH_LIMIT": 1
  },
  "nUnit": {
    "EMBARK_DISEMBARK_MULTIPLIER": 0.2,
    "SIZE_IMPACT_ON_MOVEMENT_SCALE": -0.02,
    "SIZE_IMPACT_ON_MOVEMENT_CAP": -0.5,
    "BASE_REGIMENT_PRICE_SCALE": 0.1,
    "BASE_SCALE_SHIP_DOUBLE_PER_AGE": 1,
    "EXPERIENCE_GAIN_FROM_MISSIONS": 1,
    "UPGRADE_COST_SCALE": 0.1,
    "REGIMENT_SIZE": 1000,
    "ATTRITION_ON_FOOD_CONSUMPTION_IMPACT": 2,
    "MAX_FOOD_CONSUMPTION_PENALTY": 3,
    "MONTHS_OF_FOOD_FOR_DETACHED_SUPPORT": 6,
    "ATTRITION_LACK_OF_FOOD": 5,
    "LEVY_MAINTENANCE_FACTOR": 0.01,
    "MOTHBALL_PERCENT": 0.1,
    "LAND_MORALE": 3,
    "NAVAL_MORALE": 3,
    "ARMY_MOVEMENT_SPEED": 0.13,
    "NAVY_MOVEMENT_SPEED": 0.5,
    "ARMY_MOVEMENT_SPEED_INTO_UNKNOWN_TERRITORY_MODIFIER": 1,
    "MOVEMENT_LOCKED": 0.5,
    "LOW_MORALE_THRESHOLD": 0.5,
    "SHIP_UPGRADE_STARTING_STRENGTH": 0.01,
    "MONTHLY_REINFORCE": 0.25,
    "MONTHLY_REPAIR": 0.1,
    "LOCKED_MORALE_CAP": 0.5,
    "LAND_MERC_COMPANY_RANDOM_NAME_COUNT": 20,
    "NAVAL_MERC_COMPANY_RANDOM_NAME_COUNT": 4,
    "LEADER_ASSIGN_MIN_DAYS": 7,
    "LEADER_ASSIGN_DISTANCE_FACTOR": 0.07,
    "NAVAL_ATTRITION_CHANCE": 0.1,
    "NAVAL_ATTRITION_MIN_AT_PORT": 0.05,
    "DAYS_UNTIL_CAN_BE_RANSOMED_AGAIN": 60,
    "ATTRITION_DAYS_AT_SEA": 0.02,
    "OUTSIDE_OF_NAVAL_RANGE_ATTRITION": 0.5,
    "FROZEN_ATTRITION": 0.5,
    "FALLING_THROUGH_ICE_MIN_PROPORTION_TO_ESCAPE": 0.5,
    "DEPOSIT_FOOD_FRACTION": 0.25,
    "SUPPLY_DEPOT_FOOD_FRACTION": 0.5,
    "PATHFIND_NON_COASTAL_PENALTY_FACTOR": 10,
    "DISEMBARK_COST_MULTIPLIER": 0.5,
    "LOCATION_SCALE_ON_MOVEMENT_COST": 1.33,
    "PERCENTAGE_OF_REGIMENTS_WITH_NICKNAME": 0.5,
    "PATHFIND_FROZEN_PENALTY_FACTOR": 20
  },
  "baseFrontage": 10,
  "topography": {
    "flatland": {
      "defenderDice": 0,
      "frontageDelta": 0
    },
    "mountains": {
      "defenderDice": 2,
      "frontageDelta": -4
    },
    "hills": {
      "defenderDice": 1,
      "frontageDelta": -3
    },
    "plateau": {
      "defenderDice": 1,
      "frontageDelta": -1
    },
    "wetlands": {
      "defenderDice": 1,
      "frontageDelta": -3
    },
    "salt_pans": {
      "defenderDice": 0,
      "frontageDelta": 0
    }
  },
  "vegetation": {
    "desert": {
      "defenderDice": 0,
      "frontageDelta": 0
    },
    "sparse": {
      "defenderDice": 0,
      "frontageDelta": 0
    },
    "grasslands": {
      "defenderDice": 0,
      "frontageDelta": 0
    },
    "farmland": {
      "defenderDice": 0,
      "frontageDelta": 0
    },
    "woods": {
      "defenderDice": 1,
      "frontageDelta": -2
    },
    "forest": {
      "defenderDice": 1,
      "frontageDelta": -3
    },
    "jungle": {
      "defenderDice": 1,
      "frontageDelta": -4
    }
  },
  "locationRanks": {
    "megalopolis": {
      "frontageDelta": -3
    },
    "city": {
      "frontageDelta": -2
    },
    "town": {
      "frontageDelta": -1
    },
    "rural_settlement": {
      "frontageDelta": 0
    }
  },
  "formations": {
    "balanced_army": {
      "isDefault": true,
      "sections": {
        "left": {
          "weights": {
            "army_light_cavalry": 2,
            "army_heavy_cavalry": 2,
            "army_artillery": 2,
            "army_heavy_infantry": 2,
            "army_light_infantry": 2
          },
          "maxFrontage": 1.25
        },
        "center": {
          "weights": {
            "army_light_cavalry": 2,
            "army_heavy_cavalry": 2,
            "army_artillery": 2,
            "army_heavy_infantry": 2,
            "army_light_infantry": 2
          },
          "maxFrontage": 1.25
        },
        "right": {
          "weights": {
            "army_light_cavalry": 2,
            "army_heavy_cavalry": 2,
            "army_artillery": 2,
            "army_heavy_infantry": 2,
            "army_light_infantry": 2
          },
          "maxFrontage": 1.25
        },
        "reserves": {
          "weights": {
            "army_auxiliary": 100
          },
          "maxFrontage": null
        }
      }
    },
    "cav_inf_cav": {
      "isDefault": false,
      "sections": {
        "left": {
          "weights": {
            "army_heavy_cavalry": 10,
            "army_light_cavalry": 10
          },
          "maxFrontage": 1.25
        },
        "center": {
          "weights": {
            "army_artillery": 2,
            "army_heavy_infantry": 20,
            "army_light_infantry": 20
          },
          "maxFrontage": 1.25
        },
        "right": {
          "weights": {
            "army_heavy_cavalry": 10,
            "army_light_cavalry": 10
          },
          "maxFrontage": 1.25
        },
        "reserves": {
          "weights": {
            "army_auxiliary": 100
          },
          "maxFrontage": null
        }
      }
    }
  },
  "generalTraits": {
    "glory_seeker": {},
    "born_to_the_saddle": {
      "army_light_cavalry_power": 0.1,
      "army_heavy_cavalry_power": 0.1
    },
    "offensive_planner": {
      "commander_combat_bonus": 1
    },
    "defensive_planner": {
      "military_tactics": 0.1
    },
    "battlefield_medic": {},
    "ruthless": {},
    "inspirational_leader_general": {},
    "master_of_arms": {
      "army_heavy_infantry_power": 0.1
    },
    "goal_oriented": {},
    "hardy_warrior": {},
    "siege_specialist": {},
    "cannoneer": {
      "army_artillery_power": 0.1
    },
    "unsuited_for_army_command": {
      "commander_combat_bonus": -1
    },
    "military_theorist": {
      "military_tactics": 0.05,
      "army_initiative": 0.2
    },
    "strategist": {
      "commander_combat_bonus": 2,
      "discipline": 0.1
    },
    "mamluk": {
      "land_morale_modifier": 0.1
    },
    "dragon_tiger": {
      "commander_combat_bonus": 1,
      "discipline": 0.1
    },
    "hussar_commander": {
      "commander_combat_bonus": 1,
      "army_heavy_cavalry_power": 0.25
    },
    "triumphant": {
      "commander_combat_bonus": 1,
      "discipline": 0.075,
      "military_tactics": 0.05
    }
  }
};
