// GENERATED by tools/battle-sim-reference/generate-unknowns.ts from
// specs/019-battle-simulator/combat-unknowns.md — do not edit by hand.

export interface CombatUnknown { title: string; assumption: string; status: string }

export const COMBAT_UNKNOWNS: Record<string, CombatUnknown> = {
  "U-01": {
    "title": "How the strength damage dice impact is built",
    "assumption": "dice = clamp(COMBAT_BASE + roll − 1 + mods, 0, COMBAT_MAX); strength impact = dice × 2 (STRENGTH_DICE_SLOPE, the only non-define part). 2026-09-26: the wiki's 10 + (roll−1)×2 equals exactly (COMBAT_BASE + roll − 1) × 2, so base 5 is confirmed as the define; the ×2 slope and the clamp are still unconfirmed",
    "status": "partial"
  },
  "U-02": {
    "title": "How the morale damage dice impact is built",
    "assumption": "Morale impact = dice × COMBAT_DAMAGE_MULT × BASE_MORALE_DAMAGE × LAND_MORALE_DAMAGE_MODIFIER. 2026-09-26: the wiki's 0.05 + (roll−1)×0.01 equals exactly COMBAT_DAMAGE_MULT × (COMBAT_BASE + roll − 1), so both parts are defines; how the last two multipliers combine is still unconfirmed",
    "status": "partial"
  },
  "U-03": {
    "title": "Where LAND_STRENGTH_DAMAGE_MODIFIER = 0.2 enters the chain",
    "assumption": "A final multiplier on strength damage",
    "status": "open"
  },
  "U-04": {
    "title": "Whether the effective roll is clamped (below 1 or 0? capped at COMBAT_MAX?)",
    "assumption": "Clamp to [0, COMBAT_MAX]",
    "status": "open"
  },
  "U-05": {
    "title": "Which side the terrain defender value applies to (attacker penalty or defender bonus)",
    "assumption": "Subtract from the attacker (differs from a defender bonus only under clamping, U-04)",
    "status": "open"
  },
  "U-06": {
    "title": "Whether topography and vegetation defender values add together",
    "assumption": "They add (mountains + forest = 3)",
    "status": "open"
  },
  "U-07": {
    "title": "What the commander combat bonus applies to",
    "assumption": "Added to that side's effective roll for both strength and morale damage",
    "status": "partial"
  },
  "U-08": {
    "title": "The granularity of a dice roll: one per side, per section, or per regiment?",
    "assumption": "One roll per side per phase",
    "status": "partial"
  },
  "U-09": {
    "title": "The military tactics formula",
    "assumption": "Damage taken ÷ (1 + tactics)",
    "status": "open"
  },
  "U-10": {
    "title": "Discipline on offense and defense",
    "assumption": "Damage done × (1 + discipline); damage taken ÷ (1 + discipline)",
    "status": "open"
  },
  "U-11": {
    "title": "Experience reduction and scale",
    "assumption": "Damage taken × (1 − exp/100 × 0.5)",
    "status": "open"
  },
  "U-12": {
    "title": "Unit-type power (army_*_power) and the wiki's defender-side type factors (cavalry 0.75, artillery 1.25)",
    "assumption": "Power: attacker's damage done × (1 + power). The 0.75/1.25 factors are not applied until sourced",
    "status": "open"
  },
  "U-13": {
    "title": "Flanking ability semantics (values 0.2–2.1; wiki says \"100% = no bonus\")",
    "assumption": "Damage × flanking ability, only when the target is in a different section",
    "status": "open"
  },
  "U-14": {
    "title": "Secure flanks value",
    "assumption": "Damage taken × (1 − stat per secured neighbour section)",
    "status": "open"
  },
  "U-15": {
    "title": "Whether levy combat efficiency (0.75) is offense only",
    "assumption": "Applies to damage done only",
    "status": "open"
  },
  "U-16": {
    "title": "The direction of the not-engaged bonus (1.1 strength / 1.2 morale)",
    "assumption": "Extra damage *taken* by units that are not engaged (hit while in reserve)",
    "status": "open"
  },
  "U-17": {
    "title": "How the unit stats *_damage_done / *_damage_taken combine",
    "assumption": "Multiply by (1 + value)",
    "status": "partial"
  },
  "U-18": {
    "title": "Terrain penalties per unit type (for example cavalry −10% in mountains)",
    "assumption": "Not applied until sourced",
    "status": "open"
  },
  "U-19": {
    "title": "How artillery combat power scales, in the combat phase and in bombard (\"deals its combat power as damage\")",
    "assumption": "Same strength formula as other units; bombard uses combat power × strength with no dice",
    "status": "open"
  },
  "U-20": {
    "title": "Whether base frontage 10 is per section or total",
    "assumption": "Per front section; flanks may overstack to 1.25×",
    "status": "open"
  },
  "U-21": {
    "title": "How formation preference weights place regiments (2 = army_light_cavalry: a priority or a ratio?)",
    "assumption": "Weights are relative priorities. Regiments fill sections in order of weight until each section's frontage is full; the rest go to reserves",
    "status": "open"
  },
  "U-22": {
    "title": "The engagement chance formula (three sources disagree)",
    "assumption": "Use the defines form",
    "status": "partial"
  },
  "U-23": {
    "title": "Reserve movement",
    "assumption": "Chance = 0.05 × combat speed (the same as d20 < speed when speed is an integer)",
    "status": "partial"
  },
  "U-24": {
    "title": "Target selection inside a section",
    "assumption": "Random target in the opposing section; if that is empty, the adjacent section",
    "status": "open"
  },
  "U-25": {
    "title": "Whether a regiment's save box is its battle section",
    "assumption": "Absent box ⇒ center; Left/Right/Reserves map directly; Captured regiments are left out of the pre-fill (not under the owner's command). Still unconfirmed that this is the *battle* section rather than a formation slot",
    "status": "partial"
  },
  "U-26": {
    "title": "When an individual regiment withdraws",
    "assumption": "A regiment withdraws at 0 morale and doesn't come back",
    "status": "open"
  },
  "U-27": {
    "title": "What the army's frontage=5 field means",
    "assumption": "Ignored (probably a cached UI value)",
    "status": "open"
  },
  "U-28": {
    "title": "Max morale",
    "assumption": "Max = 3.0 × (1 + land_morale_modifier)",
    "status": "open"
  },
  "U-29": {
    "title": "The hourly morale drain (COMBAT_HOURLY_MORALE_TICK=0.01): flat or scaled, engaged only?",
    "assumption": "Flat 0.01 for engaged regiments",
    "status": "partial"
  },
  "U-30": {
    "title": "What MORALE_COLLAPSE_THRESHOLD=0.05 is measured against",
    "assumption": "The side routs when average morale ≤ 5% of max",
    "status": "open"
  },
  "U-31": {
    "title": "The meaning of MINIMUM_COMBAT_DURATION=24 (hours)",
    "assumption": "No rout before hour 24; a stackwipe can still end it earlier",
    "status": "open"
  },
  "U-32": {
    "title": "Stackwipe rules (only 0 men, or an overwhelming ratio as in EU4?)",
    "assumption": "0 strength only",
    "status": "wrong"
  },
  "U-33": {
    "title": "Whether retreat damage (RETREAT_STRENGTH_DAMAGE=0.1) counts in the battle's casualties",
    "assumption": "Applied to the loser after the battle, shown separately, excluded from casualties",
    "status": "open"
  },
  "U-34": {
    "title": "Imprisoned men (in the battle record's imprisoned array)",
    "assumption": "Not modelled",
    "status": "open"
  },
  "U-35": {
    "title": "The bombard fire chance",
    "assumption": "Chance = 0.2 + bombard efficiency (0 unless the user sets it)",
    "status": "open"
  },
  "U-36": {
    "title": "How the artillery_barrage unit stat is used",
    "assumption": "Not used in 019",
    "status": "open"
  },
  "U-37": {
    "title": "When bombard happens (only at the start, or also later?)",
    "assumption": "Only the first 5 hours; skipped if neither side has artillery",
    "status": "partial"
  },
  "U-38": {
    "title": "The combat effect of the mil skill",
    "assumption": "Not applied; shown as \"effect not modelled\"",
    "status": "open"
  },
  "U-39": {
    "title": "Whether a general trait's non-dice modifiers (for example discipline = 0.1) apply to the army",
    "assumption": "They add to the side's stats while that general leads",
    "status": "partial"
  },
  "U-40": {
    "title": "Regiment strength vs number",
    "assumption": "Men = strength × REGIMENT_SIZE; number is ignored. Knock-on for 012 (not fixed in 019): Firepower's listRegimentSummaryArrow sums number as total_number, which Army Stats shows as \"headcount\" and levy/regular totals and Navy Stats uses as ship counts. If number is an ordinal, those figures are wrong. Flagged to the owner on 2026-09-26",
    "status": "partial"
  },
  "U-41": {
    "title": "The slot order and units of the battle record's 10-slot arrays (total / losses)",
    "assumption": "Slots follow unit_categories file order; values are in thousands",
    "status": "partial"
  },
  "U-42": {
    "title": "What result=yes in a battle record means",
    "assumption": "yes = the battle's attacker won",
    "status": "confirmed"
  },
  "U-43": {
    "title": "How complete the nation-level stats are (012's discipline and tactics are partial totals: no characters or leaders)",
    "assumption": "Carried over, and flagged in the UI",
    "status": "open"
  },
  "U-44": {
    "title": "Whether levy status belongs to a regiment or to its unit type",
    "assumption": "By unit type",
    "status": "partial"
  },
  "U-45": {
    "title": "Whether auxiliary (supply) regiments take part in combat",
    "assumption": "They stay in reserves, never engage, and aren't counted in strength, morale, or casualties. Added 2026-09-26 during implementation",
    "status": "partial"
  },
  "U-46": {
    "title": "What a missing strength line on a regiment means",
    "assumption": "Pre-filled as 0% strength with source default (visible and editable, never labelled as save data), so they don't fight unless the user edits them",
    "status": "open"
  },
  "U-47": {
    "title": "Whether averaging strength and experience within a composition row changes the outcome",
    "assumption": "Averaging is harmless because damage is linear in men. Total men are preserved; the spread between regiments is lost",
    "status": "open"
  },
  "U-48": {
    "title": "Whether an overwhelming-odds battle ends with a fixed 40% loss for the loser",
    "assumption": "Not modelled. The simulator fights such battles out normally, which is a known mismatch",
    "status": "open"
  },
  "U-49": {
    "title": "Losing-side casualty scale in contested battles",
    "assumption": "Unknown mechanism: morale may break too fast (U-28, U-29, U-30), damage may be too low (U-01, U-03), or there may be a pursuit/retreat loss (U-33). Not tuned",
    "status": "open"
  }
};
